name: DyrtCraftHorses
version: Release 1.0
website: http://dyrtcraft.pl/
author: TheMolkaPL
description: Plugin stworzony specjalnie dla DyrtCraft Network!

main: pl.DyrtCraft.DyrtCraftHorses.DyrtCraftHorses